services:
  frontend:
    build: ./frontend
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./BackendAPI/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8088:8080
    
  db:
    image: mariadb:12
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  proxy:
    image: caddy:2-alpine
    restart: always
    volumes:
      - ./docker/caddy_conf:/etc/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "8080:80"
      - "8443:443"

volumes:
  db_data:
  caddy_data:
  caddy_config:
